name: PR Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    uses: ./.github/workflows/_pipeline.yml
    with:
      mode: pr
      source: all
    secrets: inherit
