name: Runtime Smoke

on:
  push:
    branches:
      - main

jobs:
  health-idnes:
    if: github.event.head_commit.message == 'Run Level 5 runtime smoke'
    uses: ./.github/workflows/_pipeline.yml
    with:
      mode: health
      source: idnes
    secrets: inherit

  debug-idnes:
    if: github.event.head_commit.message == 'Run Level 5 runtime smoke'
    uses: ./.github/workflows/_pipeline.yml
    with:
      mode: debug
      source: idnes
    secrets: inherit

  production:
    if: github.event.head_commit.message == 'Run Level 5 runtime smoke'
    uses: ./.github/workflows/_pipeline.yml
    with:
      mode: production
      source: all
    secrets: inherit
